version: '3'

tasks:
  build:
    cmds:
      - rm -rf ./dist
      - mkdir -p ./dist
      - go run ./html
      - cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./dist/wasm_exec.js
      - GOOS=js GOARCH=wasm go build -o ./dist/main.wasm

  deploy:
    deps: [build]
    cmds:
      - aws s3 cp ./dist/index.html   s3://gogogo-frontend-files/index.html
      - aws s3 cp ./dist/wasm_exec.js s3://gogogo-frontend-files/wasm_exec.js

      # 参考: https://stackoverflow.com/questions/51033550/how-to-manually-gzip-files-for-web-and-amazon-cloudfront
      - gzip ./dist/main.wasm
      - aws s3 cp ./dist/main.wasm.gz s3://gogogo-frontend-files/main.wasm --content-encoding gzip --content-type application/wasm
