version: '3'

tasks:
  build:
    cmds:
      - rm -rf ./dist
      - mkdir -p ./dist
      - go run ./buildhtml
      - cp $(go env GOROOT)/misc/wasm/wasm_exec.js ./dist/wasm_exec.js
      - GOOS=js GOARCH=wasm go build -o ./dist/main.wasm

  deploy:
    deps: [build]
    cmds:
      - aws s3 sync --delete ./dist/ s3://gogogo-frontend-files
