version: '3'

tasks:
  build:
    env:
      GOARCH: amd64
      GOOS: linux
    cmds:
      - go build -ldflags="-s -w" -o dist/api        ./pkg/handlers/api/lambda
      - go build -ldflags="-s -w" -o dist/updatecats ./pkg/handlers/updatecats
