name: aws configure
description: ""

runs:
  using: composite
  steps:
    - name: aws configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
