name: aws configure
description: ""

inputs:
  aws-iam-role-arn:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: aws configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ inputs.aws-iam-role-arn }}
