name: setup golang
description: ""

inputs:
  working-directory:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        cache: true
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum
    - name: go mod download
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod download -x
