name: setup terraform
description: ""

runs:
  using: composite
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.3
        terraform_wrapper: false
