name: build

on:
  workflow_call:
    secrets:
      AWS_IAM_ROLE_ARN:
        required: true
      CAT_API_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd
    steps:
      # setup
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: cicd/go.mod
          cache: true
          cache-dependency-path: cicd/go.sum

      # build
      - name: build
        env:
          GITHUB_BRANCH: ${{ github.ref }}
        run: go run ./pkg/handlers/build
