name: build (dev)

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: cicd
    steps:
      # setup
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: cicd/go.mod
          cache: true
          cache-dependency-path: cicd/go.sum
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      # build
      - name: build
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
          CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
          GITHUB_BRANCH: ${{ github.ref }}
        run: go run ./pkg/handlers/build
