name: build

on:
  push:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
          cache-dependency-path: backend/go.sum
      - name: build
        env:
          GOARCH: amd64
          GOOS: linux
        run: go build -ldflags="-s -w" -o dist/api pkg/handlers/api/lambda/main.go
      - name: upload binary
        uses: actions/upload-artifact@v3
        with:
          name: api-binary
          path: backend/dist/api

  deploy_infrastructure:
    runs-on: ubuntu-latest
    needs: [build_backend]
    defaults:
      run:
        working-directory: infrastructure
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: download api binary
        uses: actions/download-artifact@v3
        with:
          name: api-binary
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: infrastructure/yarn.lock
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
          cache-dependency-path: infrastructure/go.sum
      - name: go mod download
        run: go mod download -x
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.3
          terraform_wrapper: false
      - name: apply
        run: yarn apply:auto-approve

  deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
          cache-dependency-path: frontend/go.sum
      - name: install go-task
        uses: arduino/setup-task@v1
      - name: deploy
        run: task deploy
