name: build

on:
  push:
    branches:
      - main
      - cicd # TODO: debug 用。消す。

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/_workflow.yml
    secrets: inherit
    with:
      workflow: deploy
